/*
Copyright 2026 The Kubernetes Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ContainerImageSourceApplyConfiguration represents a declarative configuration of the ContainerImageSource type for use
// with apply.
//
// ContainerImageSource defines a container image source.
type ContainerImageSourceApplyConfiguration struct {
	// Ref is the container image containing the MCP server implementation.
	// Must be a valid OCI image reference.
	// Examples:
	// - ghcr.io/modelcontextprotocol/servers/filesystem:latest
	// - ghcr.io/modelcontextprotocol/servers/github:v1.0.0
	// - custom-registry.io/my-mcp-server:1.2.3
	// - custom-registry.io/my-mcp-server@sha256:1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef
	Ref *string `json:"ref,omitempty"`
}

// ContainerImageSourceApplyConfiguration constructs a declarative configuration of the ContainerImageSource type for use with
// apply.
func ContainerImageSource() *ContainerImageSourceApplyConfiguration {
	return &ContainerImageSourceApplyConfiguration{}
}

// WithRef sets the Ref field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ref field is set to the value of the last call.
func (b *ContainerImageSourceApplyConfiguration) WithRef(value string) *ContainerImageSourceApplyConfiguration {
	b.Ref = &value
	return b
}
