/*
Copyright 2026 The Kubernetes Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// MCPServerStatusApplyConfiguration represents a declarative configuration of the MCPServerStatus type for use
// with apply.
//
// MCPServerStatus defines the observed state of MCPServer.
type MCPServerStatusApplyConfiguration struct {
	// Phase represents the current lifecycle phase of the MCPServer.
	// Possible values: Pending, Running, Failed
	Phase *string `json:"phase,omitempty"`
	// DeploymentName is the name of the Deployment created for this MCPServer.
	DeploymentName *string `json:"deploymentName,omitempty"`
	// ServiceName is the name of the Service created for this MCPServer.
	ServiceName *string `json:"serviceName,omitempty"`
	// Address contains the address of the MCP server service.
	Address *MCPServerAddressApplyConfiguration `json:"address,omitempty"`
	// Conditions represent the current state of the MCPServer resource.
	// Each condition has a unique type and reflects the status of a specific aspect of the resource.
	//
	// Standard condition types include "Ready", "Progressing", and "Degraded".
	// The "Ready" condition indicates the resource is fully functional and available.
	// The "Progressing" condition indicates the resource is being created or updated.
	// The "Degraded" condition indicates the resource failed to reach or maintain its desired state.
	//
	// The status of each condition is one of True, False, or Unknown.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// MCPServerStatusApplyConfiguration constructs a declarative configuration of the MCPServerStatus type for use with
// apply.
func MCPServerStatus() *MCPServerStatusApplyConfiguration {
	return &MCPServerStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *MCPServerStatusApplyConfiguration) WithPhase(value string) *MCPServerStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithDeploymentName sets the DeploymentName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeploymentName field is set to the value of the last call.
func (b *MCPServerStatusApplyConfiguration) WithDeploymentName(value string) *MCPServerStatusApplyConfiguration {
	b.DeploymentName = &value
	return b
}

// WithServiceName sets the ServiceName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceName field is set to the value of the last call.
func (b *MCPServerStatusApplyConfiguration) WithServiceName(value string) *MCPServerStatusApplyConfiguration {
	b.ServiceName = &value
	return b
}

// WithAddress sets the Address field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Address field is set to the value of the last call.
func (b *MCPServerStatusApplyConfiguration) WithAddress(value *MCPServerAddressApplyConfiguration) *MCPServerStatusApplyConfiguration {
	b.Address = value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *MCPServerStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *MCPServerStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
