/*
Copyright 2026 The Kubernetes Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/kubernetes-sigs/mcp-lifecycle-operator/api/v1alpha1"
	v1 "k8s.io/api/core/v1"
)

// StorageSourceApplyConfiguration represents a declarative configuration of the StorageSource type for use
// with apply.
//
// StorageSource defines the source of the storage to mount (ConfigMap or Secret).
type StorageSourceApplyConfiguration struct {
	// Type is a required field that specifies the type of volume source.
	// Allowed values are: ConfigMap, Secret.
	// This determines which volume source field (configMap or secret) should be configured.
	Type *apiv1alpha1.StorageType `json:"type,omitempty"`
	// ConfigMap specifies a ConfigMap volume source (when Type is ConfigMap).
	// Uses native Kubernetes ConfigMapVolumeSource type for full feature parity.
	ConfigMap *v1.ConfigMapVolumeSource `json:"configMap,omitempty"`
	// Secret specifies a Secret volume source (when Type is Secret).
	// Uses native Kubernetes SecretVolumeSource type for full feature parity.
	Secret *v1.SecretVolumeSource `json:"secret,omitempty"`
}

// StorageSourceApplyConfiguration constructs a declarative configuration of the StorageSource type for use with
// apply.
func StorageSource() *StorageSourceApplyConfiguration {
	return &StorageSourceApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *StorageSourceApplyConfiguration) WithType(value apiv1alpha1.StorageType) *StorageSourceApplyConfiguration {
	b.Type = &value
	return b
}

// WithConfigMap sets the ConfigMap field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConfigMap field is set to the value of the last call.
func (b *StorageSourceApplyConfiguration) WithConfigMap(value v1.ConfigMapVolumeSource) *StorageSourceApplyConfiguration {
	b.ConfigMap = &value
	return b
}

// WithSecret sets the Secret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Secret field is set to the value of the last call.
func (b *StorageSourceApplyConfiguration) WithSecret(value v1.SecretVolumeSource) *StorageSourceApplyConfiguration {
	b.Secret = &value
	return b
}
