apiVersion: mcp.x-k8s.io/v1alpha1
kind: MCPServer
metadata:
  labels:
    app.kubernetes.io/name: mcp-lifecycle-operator
    app.kubernetes.io/managed-by: kustomize
  name: mcpserver-sample
spec:
  # TODO(user): Add fields here
